// <auto-generated />
namespace WPF_Zoo_Manager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class CodeFirst : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CodeFirst));
        
        string IMigrationMetadata.Id
        {
            get { return "202506171443475_Code-First"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
